name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Run test-runner
        run: docker compose run test-runner
